"""add_timestamps_to_students

Revision ID: 22a9a99475e8
Revises: d80296832cc3
Create Date: 2025-12-01 10:11:36.994473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a9a99475e8'
down_revision = 'd80296832cc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'created_at')
    # ### end Alembic commands ###
