"""add_timestamps_to_students

Revision ID: 80c9fadf39db
Revises: 22a9a99475e8
Create Date: 2025-12-01 10:11:59.562050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c9fadf39db'
down_revision = '22a9a99475e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
